# Generated by Django 4.1 on 2022-09-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seeds", "0002_rename_user_audioclip_owner_rename_user_blob_owner_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Label",
        ),
    ]
