name: Run backend unit tests
on: push

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
    run: |
      pip3 install --user -r backend/requirements.txt
      python3 manage.py test
      