name: Run Backend Unit Tests
on: [push, pull_request]
jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by a ${{ github.event_name }} event"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run Django unit tests
        run: |
          pip3 install --user -r backend/requirements.txt
          export DJANGO_SETTINGS_MODULE="config.settings.dev"
          python3 backend/manage.py test
      
          